version: 0.2
environment_variables:
  plaintext:
    S3_BUCKET: 'robot-bucket1'
    BUILD_ENV: 'prod' # this should be an env variable
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `today`
      - ng build --prod
  post_build:
    commands:
      - aws s3 cp ./dist/app s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: './dist/app'
  discard-paths: yes